"""
Hyperledger Fabric Gateway Client

Connects to the SmartLedger Fabric peer via gRPC (Fabric Gateway API, Fabric 2.4+).
Used by the Ledger MCP server when write_guard=False (Phase 1+).

The Gateway API uses three pieces of identity material loaded from the filesystem
(generated by the setup-fabric.sh script):
  - The signer identity (X.509 certificate) — proves who is submitting
  - The signing key (private key) — signs transaction proposals
  - The TLS root cert of the peer — validates the TLS connection

Configuration (via .env / Settings):
  FABRIC_PEER_ENDPOINT      e.g. "localhost:7051"
  FABRIC_CHANNEL            e.g. "smartledger-channel"
  FABRIC_CHAINCODE          e.g. "smartledger-cc"
  FABRIC_MSP_ID             e.g. "SmartLedgerOrgMSP"
  FABRIC_CERT_PATH          Path to PEM client certificate
  FABRIC_KEY_PATH           Path to PEM private key
  FABRIC_TLS_CERT_PATH      Path to peer TLS root cert PEM
"""

from __future__ import annotations

import asyncio
import json
from pathlib import Path
from typing import Any

from shared.logging import get_logger

logger = get_logger(__name__)

# fabric-gateway is an optional runtime dependency (only needed in Phase 1+).
# Import lazily so the Ledger MCP can still start in Phase 0 even if the
# package is not installed.
try:
    import grpc
    from grpc import ssl_channel_credentials
    from fabric_sdk_py.gateway import connect as _fabric_connect

    _FABRIC_AVAILABLE = True
except ImportError:
    _FABRIC_AVAILABLE = False


class FabricClient:
    """
    Async wrapper around the Hyperledger Fabric Gateway client.

    Provides two operations matching the SmartLedger chaincode:
      - write_record(...)          → submit WriteRecord transaction
      - execute_state_transition() → submit ExecuteStateTransition transaction

    Both return the transaction ID (fabric_tx_id) on success.

    The client is NOT thread-safe. Create one per process and call methods
    from a single event loop.
    """

    def __init__(
        self,
        peer_endpoint: str,
        channel: str,
        chaincode: str,
        msp_id: str,
        cert_path: str,
        key_path: str,
        tls_cert_path: str,
    ) -> None:
        self._peer_endpoint = peer_endpoint
        self._channel       = channel
        self._chaincode     = chaincode
        self._msp_id        = msp_id
        self._cert_path     = cert_path
        self._key_path      = key_path
        self._tls_cert_path = tls_cert_path
        self._connection     = None

    # ── Lifecycle ──────────────────────────────────────────────────────────────

    async def connect(self) -> None:
        """Open the gRPC connection to the peer."""
        if not _FABRIC_AVAILABLE:
            raise RuntimeError(
                "fabric-sdk-py is not installed. "
                "Run: uv add fabric-sdk-py --package smartledger-ledger"
            )

        cert_pem     = Path(self._cert_path).read_bytes()
        key_pem      = Path(self._key_path).read_bytes()
        tls_cert_pem = Path(self._tls_cert_path).read_bytes()

        credentials = ssl_channel_credentials(
            root_certificates=tls_cert_pem,
            private_key=key_pem,
            certificate_chain=cert_pem,
        )

        self._grpc_channel = grpc.aio.secure_channel(
            self._peer_endpoint,
            credentials,
        )

        logger.info(
            "fabric_client_connecting",
            peer=self._peer_endpoint,
            channel=self._channel,
            chaincode=self._chaincode,
        )

    async def close(self) -> None:
        """Close the gRPC connection."""
        if self._grpc_channel:
            await self._grpc_channel.close()
            self._grpc_channel = None

    # ── Transactions ───────────────────────────────────────────────────────────

    async def write_record(
        self,
        record_id:    str,
        contract_id:  str,
        record_type:  str,
        data_hash:    str,
        payload:      dict[str, Any],
        timestamp:    str,
    ) -> str:
        """
        Submit a WriteRecord transaction to the Fabric ledger.

        Returns the Fabric transaction ID (fabric_tx_id).
        """
        payload_json = json.dumps(payload)

        result = await self._submit_transaction(
            "WriteRecord",
            record_id,
            contract_id,
            record_type,
            data_hash,
            payload_json,
            timestamp,
        )

        data = json.loads(result)
        tx_id = data.get("tx_id", "")
        logger.info(
            "fabric_record_written",
            record_id=record_id,
            contract_id=contract_id,
            record_type=record_type,
            tx_id=tx_id,
        )
        return tx_id

    async def execute_state_transition(
        self,
        contract_id:      str,
        new_state:        str,
        trigger_event_id: str,
        saga_id:          str,
        timestamp:        str,
    ) -> str:
        """
        Submit an ExecuteStateTransition transaction.

        Returns the Fabric transaction ID.
        """
        result = await self._submit_transaction(
            "ExecuteStateTransition",
            contract_id,
            new_state,
            trigger_event_id,
            saga_id or "",
            timestamp,
        )

        data  = json.loads(result)
        tx_id = data.get("tx_id", "")
        logger.info(
            "fabric_state_transition",
            contract_id=contract_id,
            new_state=new_state,
            tx_id=tx_id,
        )
        return tx_id

    # ── Queries ────────────────────────────────────────────────────────────────

    async def query_record(self, record_id: str) -> dict[str, Any]:
        """Query a single record from the Fabric ledger (read-only, no consensus)."""
        result = await self._evaluate_transaction("QueryRecord", record_id)
        return json.loads(result)

    async def get_contract_state(self, contract_id: str) -> dict[str, Any]:
        """Get the current on-chain state of a contract."""
        result = await self._evaluate_transaction("GetContractState", contract_id)
        return json.loads(result)

    # ── Internal ───────────────────────────────────────────────────────────────

    async def _submit_transaction(self, fn: str, *args: str) -> str:
        """
        Submit a transaction (requires ordering + peer endorsement).

        This wraps the synchronous fabric-sdk-py calls in a thread pool
        executor so they don't block the asyncio event loop.
        """
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(
            None,
            self._submit_transaction_sync,
            fn,
            list(args),
        )

    def _submit_transaction_sync(self, fn: str, args: list[str]) -> str:
        """Synchronous Fabric transaction submission (runs in thread pool)."""
        from hfc.fabric import Client as HFClient

        hfc = HFClient(
            net_profile=None,
            channel_name=self._channel,
        )

        # Build the transaction request
        request = {
            "fcn":  fn,
            "args": args,
        }

        # Submit via the peer endpoint
        # Note: fabric-sdk-py has its own event loop management; calling from
        # a thread pool avoids conflicts with the main asyncio loop.
        import asyncio as _asyncio
        loop = _asyncio.new_event_loop()
        try:
            result = loop.run_until_complete(
                hfc.chaincode_invoke(
                    requestor=None,
                    channel_name=self._channel,
                    peers=[self._peer_endpoint],
                    fcn=fn,
                    args=args,
                    cc_name=self._chaincode,
                    wait_for_event=True,
                )
            )
        finally:
            loop.close()

        return result if isinstance(result, str) else result.decode()

    async def _evaluate_transaction(self, fn: str, *args: str) -> str:
        """Evaluate a transaction (query only, no consensus needed)."""
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(
            None,
            self._evaluate_transaction_sync,
            fn,
            list(args),
        )

    def _evaluate_transaction_sync(self, fn: str, args: list[str]) -> str:
        from hfc.fabric import Client as HFClient
        import asyncio as _asyncio

        hfc  = HFClient(net_profile=None, channel_name=self._channel)
        loop = _asyncio.new_event_loop()
        try:
            result = loop.run_until_complete(
                hfc.chaincode_query(
                    requestor=None,
                    channel_name=self._channel,
                    peers=[self._peer_endpoint],
                    fcn=fn,
                    args=args,
                    cc_name=self._chaincode,
                )
            )
        finally:
            loop.close()

        return result if isinstance(result, str) else result.decode()


# ── Factory ────────────────────────────────────────────────────────────────────

def create_fabric_client_from_settings(settings) -> "FabricClient | None":
    """
    Create a FabricClient from Settings, or return None if Fabric is not configured.

    Returns None if any required config is missing (peer endpoint, MSP ID).
    Logs a warning so the Ledger MCP knows to stay in PostgreSQL-only mode.
    """
    if not settings.fabric_peer_endpoint or not settings.fabric_msp_id:
        logger.warning(
            "fabric_not_configured",
            peer_endpoint=settings.fabric_peer_endpoint,
            msp_id=settings.fabric_msp_id,
            hint="Set FABRIC_PEER_ENDPOINT and FABRIC_MSP_ID to enable live Fabric writes",
        )
        return None

    cert_path     = getattr(settings, "fabric_cert_path",     "")
    key_path      = getattr(settings, "fabric_key_path",      "")
    tls_cert_path = getattr(settings, "fabric_tls_cert_path", "")

    for attr, path in [("fabric_cert_path", cert_path), ("fabric_key_path", key_path), ("fabric_tls_cert_path", tls_cert_path)]:
        if not path or not Path(path).exists():
            logger.warning(
                "fabric_cert_not_found",
                attr=attr,
                path=path,
                hint=f"Run infra/fabric/scripts/setup-fabric.sh to generate crypto material, then set {attr.upper()} in .env",
            )
            return None

    return FabricClient(
        peer_endpoint=settings.fabric_peer_endpoint,
        channel=settings.fabric_channel,
        chaincode=settings.fabric_chaincode,
        msp_id=settings.fabric_msp_id,
        cert_path=cert_path,
        key_path=key_path,
        tls_cert_path=tls_cert_path,
    )
