"""
Shared configuration loaded from environment variables.
All services import from here — single source of truth for config.
"""
from functools import lru_cache
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    # ─── Phase & Mode ─────────────────────────────────────────────────────────
    phase: int = 0
    write_guard: bool = True
    log_level: str = "INFO"
    service_name: str = "smartledger"

    # ─── Infrastructure ───────────────────────────────────────────────────────
    database_url: str = "postgresql://smartledger:smartledger_dev@localhost:5432/smartledger"
    redis_url: str = "redis://localhost:6379"

    # ─── Anthropic ────────────────────────────────────────────────────────────
    anthropic_api_key: str = ""
    anthropic_model: str = "claude-3-5-sonnet-20241022"

    # ─── MCP Server URLs ──────────────────────────────────────────────────────
    # FastMCP serves at /mcp — all URLs must include the /mcp path suffix.
    mcp_validation_url: str = "http://localhost:8001/mcp"
    mcp_ledger_url: str = "http://localhost:8002/mcp"
    mcp_semantic_ai_url: str = "http://localhost:8003/mcp"
    mcp_reporting_url: str = "http://localhost:8004/mcp"

    # Simulated systems
    mcp_oracle_los_url: str = "http://localhost:8010/mcp"
    mcp_salesforce_los_url: str = "http://localhost:8011/mcp"
    mcp_llas_url: str = "http://localhost:8012/mcp"
    mcp_crm_url: str = "http://localhost:8013/mcp"
    mcp_payment_url: str = "http://localhost:8014/mcp"
    mcp_insurance_url: str = "http://localhost:8015/mcp"
    mcp_dealer_url: str = "http://localhost:8016/mcp"
    mcp_customer_portal_url: str = "http://localhost:8017/mcp"
    mcp_mobile_app_url: str = "http://localhost:8018/mcp"
    mcp_ivr_url: str = "http://localhost:8019/mcp"
    mcp_rules_engine_url: str = "http://localhost:8020/mcp"
    mcp_pricing_engine_url: str = "http://localhost:8021/mcp"
    mcp_integration_url: str = "http://localhost:8022/mcp"

    # ─── JWT (agent session tokens) ───────────────────────────────────────────
    jwt_secret: str = "change-me-in-production"
    jwt_expiry_seconds: int = 3600

    # ─── Validation Proof Tokens (single-use, 60s, Validation Engine → Ledger)
    proof_token_secret: str = "change-me-proof-token-secret"
    proof_token_expiry_seconds: int = 60

    # ─── Party-Based Access Control (Smart Data Gateway — Section 6.5) ──────
    pbac_enabled: bool = True             # Feature flag for party-based access control
    dashboard_jwt_secret: str = "change-me-dashboard-jwt-secret"  # JWT verification for Dashboard API

    # ─── Hyperledger Fabric ───────────────────────────────────────────────────
    # Network config
    fabric_peer_endpoint: str = ""                  # e.g. "localhost:7051"
    fabric_orderer_endpoint: str = "localhost:7050" # e.g. "localhost:7050"
    fabric_channel: str = "smartledger-channel"
    fabric_chaincode: str = "smartledger-cc"
    fabric_msp_id: str = ""                         # e.g. "SmartLedgerOrgMSP"
    # TLS / crypto material (generated by infra/fabric/scripts/setup-fabric.sh)
    fabric_tls_cert_path: str = ""    # peer TLS root cert PEM
    fabric_orderer_tls_path: str = "" # orderer TLS root cert PEM
    fabric_admin_msp_path: str = ""   # admin MSP directory
    fabric_cfg_path: str = ""         # dir containing core.yaml
    fabric_bin_path: str = ""         # dir containing peer binary


@lru_cache
def get_settings() -> Settings:
    return Settings()
